# Generated by Django 4.2.2 on 2023-06-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
